"""Dataset preparation CLI.

Converts `json` simulation logs into a structured `csv` dataset.
"""

import argparse

from rich.console import Console
from rich.table import Table

from agentdialogues.analytics import prepare_simulation_dataset

console = Console()


def build_dataset_from_logs(
    scenario_id: str, output_filename: str | None = None
) -> None:
    """Build dataset and print summary info."""
    table = Table(title="Dataset Preparation", header_style="bold green")
    table.add_column("Parameter", style="cyan", no_wrap=True)
    table.add_column("Value", style="white")

    table.add_row("Scenario ID", scenario_id)
    table.add_row("Output File", output_filename or f"aggregated_{scenario_id}.csv")

    console.print(table)

    output_path = prepare_simulation_dataset(
        scenario_id=scenario_id,
        output_filename=output_filename,
    )

    console.print(f"[bold cyan]✅ Dataset saved to:[/bold cyan] {output_path}")


def main() -> None:
    """Entry point for CLI."""
    parser = argparse.ArgumentParser(
        description="Aggregate simulation outputs from dialogue logs into a CSV file."
    )
    parser.add_argument(
        "--scenario",
        type=str,
        required=True,
        help="Scenario ID (directory name under logs/)",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Optional: output CSV filename (defaults to autogenerated based on scenario name)",
    )

    args = parser.parse_args()
    build_dataset_from_logs(scenario_id=args.scenario, output_filename=args.output)


if __name__ == "__main__":
    main()
